name: Terraform Pipeline

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform_Module_Security_Scan_09082026/environment/Preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run:
          az login \
            --service-principal \
            --username "fdd713fe-c04e-4f77-bf32-a6fdca444293" \
            --password "WpL8Q~JMmoubPNc2.GySYAPiEXOdgLeFXsgbdaOo" \
            --tenant "671f4d53-5b42-4115-b9b5-b124b362c106"        

      - name: VSet Azure Subscription
        run:
          az account set \
            --subscription "09e94b24-0988-4194-b9f8-911e0586f6b2"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false