name: Terraform Pipeline

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  terraform-plan:

    name: Terraform Plan

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform_Module_Security_Scan_09082026/environment/Preprod

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: 1fca1d92-f783-450c-8717-5ee79cc6397e
          tenant-id: 4196a640-eeb4-4d47-8793-18d725e31174
          subscription-id: 904cfc92-9a73-4439-90cb-6496ce28db13

      - name: Verify Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false